name: Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build lambdas and ts packages
      run: npm run compile -ws

    - name: Run the tests
      run: npm test -- --coverage
    
    - name: Storybook Tests
      run: cd packages/amplify-frontend-schema-form/ && npm run test-storybook:ci && cd ../../
      